export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:8081/api' : 'link deploy'
export const LOCAL_STORAGE_TOKEN_NAME = 'user-token'
export const POSTS_LOADED_SUCCESS = 'POSTS_LOADED_SUCCESS'
export const POSTS_LOADED_FAIL = 'POSTS_LOADED_FAIL'
export const POST_ADDED_SUCCESS = 'POST_ADDED_SUCCESS'
export const USER_ROLE = 'USER_ROLE'
export const POST_DELETED_SUCCESS = 'POST_DELETED_SUCCESS'
export const POST_ACCEPTED_SUCCESS = 'POST_ACCEPTED_SUCCESS'
export const POSTS_FIND_SUCCESS = 'POSTS_FIND_SUCCESS'
export const BEFORE_GET_PREPARE = 'BEFORE_GET_PREPARE'
export const POST_UPDATED_SUCCESS = 'POST_UPDATED_SUCCESS'




export const JOBFIELD = [
    { label: "Business Development", value: 4 },
    { label: "Aviation", value: 5 },
    { label: "Banking", value: 6 },
    { label: "Bublic Relations", value: 7 },
    { label: "Chef", value: 8 },
    { label: "Teacher", value: 9 },
    { label: "Accountant", value: 10 },
    { label: "Consultant", value: 11 },
    { label: "Digitalmedia", value: 12 },
    { label: "Apparel", value: 13 },
    { label: "Java Developer", value: 14 },
    { label: "Construction", value: 15 },
    { label: "Testing", value: 16 },
    { label: "Finance", value: 17 },
    { label: "Agriculture", value: 18 },
    { label: "Devops Engineer", value: 19 },
    { label: "Python Developer", value: 20 },
    { label: "Web Designing", value: 21 },
    { label: "HR", value: 22 },
    { label: "Hadoop", value: 23 },
    { label: "Blockchain", value: 24 },
    { label: "Mechanical Engineer", value: 25 },
    { label: "Sales", value: 26 },
    { label: "Etl Developer", value: 27 },
    { label: "Operations Manager", value: 28 },
    { label: "Data Science", value: 29 },
    { label: "Arts", value: 30 },
    { label: "Automobile", value: 31 },
    { label: "Database", value: 32 },
    { label: "Health and Fitness", value: 33 },
    { label: "PMO", value: 34 },
    { label: "Electrical Engineering", value: 35 },
    { label: "Dot Net Developer", value: 36 },
    { label: "Business Analyst", value: 37 },
    { label: "Automation Testing", value: 38 },
    { label: "Network Security Engineer", value: 39 },
    { label: "Civil Engineer", value: 40 },
    { label: "SAP Developer", value: 41 },
    { label: "BPO", value: 42 },
    { label: "Advocate", value: 43 },
    { label: "Engineering", value: 44 },   
  ]; 


  export const CITYLOCATION = [
    { value: 4, label: 'An Giang' },
    { value: 5, label: 'Ba Ria - Vung Tau' },
    { value: 6, label: 'Bac Giang' },
    { value: 7, label: 'Bac Can' },
    { value: 8, label: 'Bac Lieu' },
    { value: 9, label: 'Bac Ninh' },
    { value: 10, label: 'Ben Tre' },
    { value: 11, label: 'Binh Dinh' },
    { value: 2, label: 'Binh Duong' },
    { value: 12, label: 'Binh Phuoc' },
    { value: 13, label: 'Binh Thuan' },
    { value: 14, label: 'Ca Mau' },
    { value: 15, label: 'Can Tho' },
    { value: 16, label: 'Cao Bang' },
    { value: 17, label: 'Da Nang' },
    { value: 18, label: 'Dak Lak' },
    { value: 19, label: 'Dak Nong' },
    { value: 20, label: 'Dien Bien' },
    { value: 3, label: 'Dong Nai' },
    { value: 21, label: 'Dong Thap' },
    { value: 22, label: 'Gia Lai' },
    { value: 23, label: 'Ha Giang' },
    { value: 24, label: 'Ha Nam' },
    { value: 25, label: 'Ha Noi' },
    { value: 26, label: 'Ha Tinh' },
    { value: 27, label: 'Hai Duong' },
    { value: 28, label: 'Hai Phong' },
    { value: 29, label: 'Hau Giang' },
    { value: 30, label: 'Hoa Binh' },
    { value: 31, label: 'Hung Yen' },
    { value: 32, label: 'Khanh Hoa' },
    { value: 33, label: 'Kien Giang' },
    { value: 34, label: 'Kon Tum' },
    { value: 35, label: 'Lai Chau' },
    { value: 36, label: 'Lam Dong' },
    { value: 37, label: 'Lang Son' },
    { value: 38, label: 'Lao Cai' },
    { value: 39, label: 'Long An' },
    { value: 40, label: 'Nam Dinh' },
    { value: 41, label: 'Nghe An' },
    { value: 42, label: 'Ninh Binh' },
    { value: 43, label: 'Ninh Thuan' },  
    { value: 44, label: 'Phu Tho' },  
    { value: 45, label: 'Phu Yen' },  
    { value: 46, label: 'Quang Binh' },  
    { value: 47, label: 'Quang Nam' },  
    { value: 48, label: 'Quang Ngai' },     
    { value: 49, label: 'Quang Ninh' },  
    { value: 50, label: 'Quang Tri' },  
    { value: 51, label: 'Soc Trang' },  
    { value: 52, label: 'Son La' },  
    { value: 53, label: 'Tay Ninh' },  
    { value: 54, label: 'Thai Binh' },  
    { value: 55, label: 'Thai Nguyen' },  
    { value: 56, label: 'Thanh Hoa' },  
    { value: 57, label: 'Thua Thien Hue' },  
    { value: 58, label: 'Tien Giang' },
    { value: 1, label: 'Ho Chi Minh' },  
    { value: 59, label: 'Tra Vinh' }, 
    { value: 60, label: 'Tuyen Quang' }, 
    { value: 61, label: 'Vinh Long' }, 
    { value: 62, label: 'Vinh Phuc' }, 
    { value: 63, label: 'Yen Bai' }, 
  ];