export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:8081/api' : 'link deploy'
export const LOCAL_STORAGE_TOKEN_NAME = 'user-token'
export const POSTS_LOADED_SUCCESS = 'POSTS_LOADED_SUCCESS'
export const POSTS_LOADED_FAIL = 'POSTS_LOADED_FAIL'





export const JOBFIELD = [
    { label: "Business Development", value: 4 },
    { label: "Aviation", value: 5 },
    { label: "Banking", value: 6 },
    { label: "Bublic Relations", value: 7 },
    { label: "Chef", value: 8 },
    { label: "Teacher", value: 9 },
    { label: "Accountant", value: 10 },
    { label: "Consultant", value: 11 },
    { label: "Digitalmedia", value: 12 },
    { label: "Apparel", value: 13 },
    { label: "Java Developer", value: 14 },
    { label: "Construction", value: 15 },
    { label: "Testing", value: 16 },
    { label: "Finance", value: 17 },
    { label: "Agriculture", value: 18 },
    { label: "Devops Engineer", value: 19 },
    { label: "Python Developer", value: 20 },
    { label: "Web Designing", value: 21 },
    { label: "HR", value: 22 },
    { label: "Hadoop", value: 23 },
    { label: "Blockchain", value: 24 },
    { label: "Mechanical Engineer", value: 25 },
    { label: "Sales", value: 26 },
    { label: "Etl Developer", value: 27 },
    { label: "Operations Manager", value: 28 },
    { label: "Data Science", value: 29 },
    { label: "Arts", value: 30 },
    { label: "Automobile", value: 31 },
    { label: "Database", value: 32 },
    { label: "Health and Fitness", value: 33 },
    { label: "PMO", value: 34 },
    { label: "Electrical Engineering", value: 35 },
    { label: "Dot Net Developer", value: 36 },
    { label: "Business Analyst", value: 37 },
    { label: "Automation Testing", value: 38 },
    { label: "Network Security Engineer", value: 39 },
    { label: "Civil Engineer", value: 40 },
    { label: "SAP Developer", value: 41 },
    { label: "BPO", value: 42 },
    { label: "Advocate", value: 43 },
    { label: "Engineering", value: 44 },   
  ]; 


  const CITYLOCATION = [
    { label: "An Giang", value: 'An Giang' },
    { label: "Ba Ria - Vung Tau", value: 'Ba Ria - Vung Tau' },
    { label: "Bac Giang", value: 'Bac Giang' },
    { label: "Bac Kan", value: 'Bac Kan' },
    { label: "Bac Lieu", value: 'Bac Lieu' },
    { label: "Bac Ninh", value: 'Bac Ninh' },
    { label: "Ben Tre", value: 'Ben Tre' },
    { label: "Binh Dinh", value: 'Binh Dinh' },
    { label: "Binh Duong", value: 'Binh Duong' },
    { label: "Binh Phuoc", value: 'Binh Phuoc' },
    { label: "Binh Thuan", value: 'Binh Thuan' },
    { label: "Ca Mau", value: 'Ca Mau' },
    { label: "Can Tho", value: 'Can Tho' },
    { label: "Cao Bang", value: 'Cao Bang' },
    { label: "Da Nang", value: 'Da Nang' },
    { label: "Dak Lak", value: 'Dak Lak' },
    { label: "Dak Nong", value: 'Dak Nong' },
    { label: "Dien Bien", value: 'Dien Bien' },
    { label: "Dong Nai", value: 'Dong Nai' },
    { label: "Dong Thap", value: 'Dong Thap' },
    { label: "Gia Lai", value: 'Gia Lai' },
    { label: "Ha Giang", value: 'Ha Giang' },
    { label: "Ha Nam", value: 'Ha Nam' },
    { label: "Ha Noi", value: 'Ha Noi' },
    { label: "Ha Tinh", value: 'Ha Tinh' },
    { label: "Hai Duong", value: 'Hai Duong' },
    { label: "Hai Phong", value: 'Hai Phong' },
    { label: "Hau Giang", value: 'Hau Giang' },
    { label: "Hoa Binh", value: 'Hoa Binh' },
    { label: "Hung Yen", value: 'Hung Yen' },
    { label: "Khanh Hoa", value: 'Khanh Hoa' },
    { label: "Kien Giang", value: 'Kien Giang' },
    { label: "Kon Tum", value: 'Kon Tum' },
    { label: "Lai Chau", value: 'Lai Chau' },
    { label: "Lam Dong", value: 'Lam Dong' },
    { label: "Lang Son", value: 'Lang Son' },
    { label: "Lao Cai", value: 'Lao Cai' },
    { label: "Long An", value: 'Long An' },
    { label: "Nam Dinh", value: 'Nam Dinh' },
    { label: "Nghe An", value: 'Nghe An' },
    { label: "Ninh Binh", value: 'Ninh Binh' },
    { label: "Ninh Thuan", value: 'Ninh Thuan' },  
    { label: "Phu Tho", value: 'Phu Tho' },  
    { label: "Phu Yen", value: 'Phu Yen' },  
    { label: "Quang Binh", value: 'Quang Binh' },  
    { label: "Quang Nam", value: 'Quang Nam' },  
    { label: "Quang Ngai", value: 'Quang Ngai' },     
    { label: "Quang Ninh", value: 'Quang Ninh' },  
    { label: "Quang Tri", value: 'Quang Tri' },  
    { label: "Soc Trang", value: 'Soc Trang' },  
    { label: "Son La", value: 'Son La' },  
    { label: "Tay Ninh", value: 'Tay Ninh' },  
    { label: "Thai Binh", value: 'Thai Binh' },  
    { label: "Thai Nguyen", value: 'Thai Nguyen' },  
    { label: "Thanh Hoa", value: 'Thanh Hoa' },  
    { label: "Thua Thien Hue", value: 'Thua Thien Hue' },  
    { label: "Tien Giang", value: 'Tien Giang' },
    { label: "Thanh Pho Ho Chi Minh", value: 'Thanh Pho Ho Chi Minh' },  
    { label: "Tra Vinh", value: 'Tra Vinh' }, 
    { label: "Tuyen Quang", value: 'Tuyen Quang' }, 
    { label: "Vinh Long", value: 'Vinh Long' }, 
    { label: "Vinh Phuc", value: 'Vinh Phuc' }, 
    { label: "Yen Bai", value: 'Yen Bai' }, 
  ];